## Author: Dory Abelman
## Based on scripts from Derek Wong
## Plot ROCs for ML classifier data
## Cancer vs normal
## Original date: Aug 2023
## Updated Nov 2023, Jan 2024
## Updated March - May 2024


## Load libraries
library(caret)
library(dplyr)
library(tidyverse)
library(pROC)
library(ggpubr)

## Cancer vs normal comparison 

### Set variables

## This is the path for the plots for the machine learning outputs generated by the cancer_vs_normal_script
path <- "Final Data May 2024/Machine_learning_outputs/Cancer_vs_normal/"

files <- list.files(path = path, pattern = "\\.rds$")

classification_df <- data.frame(file = files, stringsAsFactors = FALSE)

# Extract 'type1' and 'type2' from the file names
classification_df$type1 <- sub(".*outcomes_([^_]+)_vs_.*", "\\1", classification_df$file)
classification_df$type2 <- sub(".*_vs_([^_]+)\\.rds", "\\1", classification_df$file)

# Extract the 'Analysis' column by matching the prefix before the first underscore
classification_df$Analysis <- sub("^CN_classifier_", "", sub("_outcomes_.*", "", classification_df$file))

# To work with for loop
comparisons_classification <- classification_df %>% select(type1, type2)

# Get all types but keep unique 
# Create a function to sort each pair of types
sort_pair <- function(row) {
  return(sort(c(row['type1'], row['type2'])))
}

## Remove the row with analysis "Combined_motif_methylation_PCs_all" since not using it
classification_df <- classification_df %>%
  filter(Analysis != "Combined_motif_methylation_PCs_all")

# Apply the function row-wise and store the sorted pairs in a new dataframe
sorted_comparisons <- t(apply(comparisons_classification, 1, sort_pair))
sorted_comparisons_df <- data.frame(type1 = sorted_comparisons[, 1], type2 = sorted_comparisons[, 2])

# Remove duplicates
unique_comparisons_df <- unique(sorted_comparisons_df)

for (i in 1:nrow(unique_comparisons_df)) {
  
  # Set variables from the dataframe
  type1 <- unique_comparisons_df$type1[i]
  type2 <- unique_comparisons_df$type2[i]
  
  # Create a regex pattern to match type1 and type2 in either order
  pattern_to_search <- paste0("(", type1, "_vs_", type2, "|", type2, "_vs_", type1, ")\\.rds")
  
  # List files that match the pattern
  filenames_short <- list.files(path, pattern = pattern_to_search, full.names = FALSE)
  filenames <- list.files(path, pattern = pattern_to_search, full.names = TRUE)
  
  # Extract the analysis from the dataframe
  matching_rows <- classification_df$file %in% filenames_short
  analyses <- unique(classification_df$Analysis[matching_rows])
  
  data_roc <- data.frame()
  data_auc <- data.frame()
  data_cm <- data.frame()
  
  for (j in c(1:length(filenames))) {
    ### Set variables
    file <- filenames[[j]]
    analysis <- analyses[[j]]
    
    ### Read in file
    data <- readRDS(file)
    
    ### Unlist files
    data <- unlist(data, recursive = FALSE)
    data <- bind_rows(data)
    
    ### Make confusion matrix
    data$ActualClass <- factor(data$ActualClass, levels = c(type1, type2))
    data$PredictedClass <- factor(data$PredictedClass, levels = c(type1, type2))
    cm <- confusionMatrix(data$PredictedClass, data$ActualClass)
    cm <- data.frame(Metric = analysis,
                     sensitivity = cm[["byClass"]][["Sensitivity"]],
                     specificity = cm[["byClass"]][["Specificity"]])
    
    ### Format table
    data$ActualClass <- ifelse(data$ActualClass == type2, 0, 1)
    
    ### Calculate auc and roc values
    roc <- roc(data$ActualClass, data[[type2]])
    specificity <- roc[["specificities"]]
    sensitivity <- roc[["sensitivities"]]
    sensitivity <- 1 - sensitivity
    
    roc <- as.data.frame(cbind(sensitivity, specificity))
    colnames(roc) <- c("sensitivity", "specificity")
    roc$Metric <- analysis
    
    auc <- auc(data$ActualClass, data[[type2]])
    auc <- format(signif(auc, digits = 3), nsmall = 3)
    auc <- data.frame(Metric = analysis, auc = auc)
    
    ### Append to dataframes
    data_roc <- rbind(data_roc, roc)
    data_auc <- rbind(data_auc, auc)
    data_cm <- rbind(data_cm, cm)
  }
  ### Format plotting tables
  # Consider incomplete metrics 
  
  # Function to get the appropriate labels for each unique metric
  get_labels <- function(unique_metrics) {
    label_mapping <- list(
      "DELFI_ratios" = "Fragment Ratio",
      "End_motif" = "End Motif",
      "Nucleosome_Peak" = "Nucleosome Peak",
      "Methylation" = "Methylation",
      "Combined_features_PCA" = "Combined Features PCA",
      "PCA_DELFI_ratios" = "PCA Fragment Ratio",
      "PCA_End_motif" = "PCA End Motif",
      "PCA_Insert_Size" = "PCA Insert Size",
      "PCA_Methylation" = "PCA Methylation",
      "PCA_Nucleosome_Peak" = "PCA Nucleosome Peak",
      "Combined_endmotif_methylation" = "End motif + methylation"
    )
    
    sapply(unique_metrics, function(x) label_mapping[[x]])
  }
  
  unique_metrics <- unique(data_roc$Metric)
  
  data_roc$Metric <- factor(data_roc$Metric, levels = unique_metrics, labels = get_labels(unique_metrics))
  data_auc$Metric <- factor(data_auc$Metric, levels = unique_metrics, labels = get_labels(unique_metrics))
  data_cm$Metric <- factor(data_cm$Metric, levels = unique_metrics, labels = get_labels(unique_metrics))
  
  
  ### Set theme
  theme <- theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 13), 
                 axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_blank(),
                 legend.title = element_text(size = 13),
                 legend.key = element_rect(fill = "white"),
                 legend.text = element_text(size = 7.5),
                 legend.position = "right",
                 legend.background = element_blank(),
                 axis.text = element_text(size = 13),
                 axis.title = element_text(size = 13))
  
  ### Plot the ROCs
  
  # Count the number of rows in data_auc
  n_rows <- nrow(data_auc)
  
  # Create a sequence for the y aesthetic
  y_values <- seq(0, 0.3, length.out = n_rows)
  
  # Add the y_values to data_auc
  data_auc$y_values <- y_values
  
  # Check to ensure correct number of rows 
  n_rows <- nrow(data_auc)
  
  # Define colors 
  my_color_palette <- c(
    "Fragment Ratio" = "#009E73",
    "End Motif" = "#E69F00",
    "Nucleosome Peak" = "#0072B2",
    "Methylation" = "#CC79A7",
    "Combined Features PCA" = "#6A3D9A",
    "PCA Fragment Ratio" = "#F0E442",
    "PCA End Motif" = "#D55E00",
    "PCA Insert Size" = "#56B4E9",
    "PCA Methylation" = "#999999",
    "PCA Nucleosome Peak" = "#FFB6C1",
    "End motif + methylation" = "#8B4513",
    "Combined_motif_methylation_PCs_1pct" = "#8B4513"

  )
  
  ## Overwrote with new palette while testing 
  my_color_palette <- c(
    "Combined_features_PCA" = "#6A3D9A",
    "DELFI_ratios" = "#009E73",
    "End_motif" = "#E69F00",
    "Methylation" = "#CC79A7",
    "Nucleosome_Peak" = "#0072B2",
    "PCA_DELFI_ratios" = "#F0E442",
    "PCA_End_motif" = "#D55E00",
    "PCA_Insert_Size" = "#56B4E9",
    "PCA_Methylation" = "#999999",
    "PCA_Nucleosome_Peak" = "#FFB6C1",
    "End motif + methylation" = "#8B0000",  # Dark Red
    "Combined_motif_methylation_PCs_1pct" = "#1E90FF",  # Dodger Blue
    "Combined_motif_methylation_PCs_all" = "#32CD32",  # Lime Green
    "Combined_motif_methylation_ratios_PCs_1pct" = "#FFD700"  # Gold
  )
  
  AUC_plot <- ggplot(data_roc) +
    geom_line(aes(sensitivity, specificity, group = Metric, color = Metric)) +
    geom_abline(intercept = 0, linetype = "dashed", alpha = 0.5) +
    geom_text(data = data_auc, aes(x = 0.7, y = seq(0, 0.4, length.out = n_rows), color = Metric, label = paste0(Metric, " = ", auc)), size = 4) +
    scale_color_manual(values = my_color_palette) + 
    xlab("False Positive Rate") + 
    ylab("True Positive Rate") +
    ggtitle("ROC Curves") + 
    theme +
    theme(legend.position = "none")
  AUC_plot
  
  ### Plot Performance Metrics
  CM_plot <- ggplot(data_cm) +
    geom_point(aes(sensitivity, specificity, color = Metric), size = 3) +
    geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey") +
    geom_vline(xintercept = 0.5, linetype = "dashed", color = "grey") +
    scale_color_manual(values = my_color_palette) + 
    xlab("Sensitivity") + 
    ylab("Specificity") +
    labs(color = "") +
    ggtitle("Performance") + 
    theme +
    theme(legend.position = c(0.5, 0.21)) +
    scale_y_continuous(limits = c(0,1)) +
    scale_x_continuous(limits = c(0,1)) +
    guides(color = guide_legend(ncol = 2))
  CM_plot
  
  ### Save Figure
  fig <- ggarrange(AUC_plot, CM_plot, align = "h")
  annotate_figure(fig, top = text_grob(paste0(type1, " vs ", type2), face = "bold", size = 14))
  ggsave(file.path(path, paste0("classifier_performance_", type1, " vs ", type2, "all features updated combined.pdf")), width = 9, height = 4.5)
}  
  

## Run on PCAs seperately
for (i in 1:nrow(unique_comparisons_df)) {
  
  # Set variables from the dataframe
  type1 <- unique_comparisons_df$type1[i]
  type2 <- unique_comparisons_df$type2[i]
  
  # Create a regex pattern to match type1 and type2 in either order
  pattern_to_search <- paste0("(", type1, "_vs_", type2, "|", type2, "_vs_", type1, ")\\.rds")
  
  # List files that match the pattern
  filenames_short <- list.files(path, pattern = pattern_to_search, full.names = FALSE)
  filenames <- list.files(path, pattern = pattern_to_search, full.names = TRUE)
  
  # Function to create and save plots
  create_and_save_plots <- function(data_roc, data_auc, data_cm, suffix) {
    
    # Ensure auc is numeric
    data_auc$auc <- as.numeric(as.character(data_auc$auc))
    
    # Sort data_auc by AUC in ascending order
    data_auc <- data_auc[order(data_auc$auc),]
    
    # Count the number of rows in data_auc
    n_rows <- nrow(data_auc)
    
    # Create a sequence for the y aesthetic
    y_values <- seq(0, 0.3, length.out = n_rows)
    
    # Add the y_values to data_auc
    data_auc$y_values <- y_values
    
    # Define colors 
    my_color_palette <- c(
      "Fragment Ratio" = "#1f77b4",
      "End Motif" = "#ff7f0e",
      "Nucleosome Peak" = "#2ca02c",
      "Methylation" = "#d62728",
      "Combined All Features PCs >5%" = "#9467bd",
      "PCA Fragment Ratio" = "#17becf",
      "PCA End Motif" = "#bcbd22",
      "PCA Insert Size" = "#e377c2",
      "PCA Methylation" = "#7f7f7f",
      "PCA Nucleosome Peak" = "#8c564b",
      "End Motif + Methylation PCs >1%" = "#8B0000",  # Dark Red
      "End Motif + Methylation + Ratios PCs >1%" = "#008080"  # Teal
    )
    
    AUC_plot <- ggplot(data_roc) +
      geom_line(aes(sensitivity, specificity, group = Metric, color = Metric)) +
      geom_abline(intercept = 0, linetype = "dashed", alpha = 0.5) +
      geom_text(data = data_auc, aes(x = 0.7, y = seq(0, 0.34, length.out = n_rows), color = Metric, label = paste0(Metric, " = ", auc)), size = 2.5) +
      scale_color_manual(values = my_color_palette) + 
      xlab("False Positive Rate") + 
      ylab("True Positive Rate") +
      ggtitle("ROC Curves") + 
      theme +
      theme(legend.position = "none") +
      theme(legend.text = element_text(size = 6))
      
    AUC_plot
    
    CM_plot <- ggplot(data_cm) +
      geom_point(aes(sensitivity, specificity, color = Metric), size = 3) +
      geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey") +
      geom_vline(xintercept = 0.5, linetype = "dashed", color = "grey") +
      scale_color_manual(values = my_color_palette) + 
      xlab("Sensitivity") + 
      ylab("Specificity") +
      labs(color = "") +
      ggtitle("Performance") + 
      theme +
      theme(legend.position = c(0.5, 0.21)) +
      theme(legend.text = element_text(size = 6)) +
      scale_y_continuous(limits = c(0,1)) +
      scale_x_continuous(limits = c(0,1)) +
      guides(color = guide_legend(ncol = 2))
    CM_plot
    
    fig <- ggarrange(AUC_plot, CM_plot, align = "h")
    annotate_figure(fig, top = text_grob(paste0(type1, " vs ", type2), face = "bold", size = 14))
    ggsave(file.path(path, paste0("classifier_performance_", type1, "_vs_", type2, "_", suffix, "combined updated.pdf")), width = 9, height = 4.5)
  }
  
  for (filter_type in c("all", "PCA")) {
    if (filter_type == "PCA") {
      filtered_classification_df <- classification_df %>% filter(str_detect(Analysis, "PC"))
    } else {
      filtered_classification_df <- classification_df
    }
    
    # Extract the analysis and filenames from the filtered dataframe
    filtered_filenames_short <- filtered_classification_df$file
    filtered_analyses <- filtered_classification_df$Analysis
    
    data_roc <- data.frame()
    data_auc <- data.frame()
    data_cm <- data.frame()
    
    for (j in seq_along(filenames)) {
      file <- filenames[[j]]
      filename_short <- filenames_short[[j]]
      
      if (!(filename_short %in% filtered_filenames_short)) next
      
      analysis <- filtered_analyses[filtered_filenames_short == filename_short]
      
      data <- readRDS(file)
      data <- unlist(data, recursive = FALSE)
      data <- bind_rows(data)
      
      data$ActualClass <- factor(data$ActualClass, levels = c(type1, type2))
      data$PredictedClass <- factor(data$PredictedClass, levels = c(type1, type2))
      cm <- confusionMatrix(data$PredictedClass, data$ActualClass)
      cm <- data.frame(Metric = analysis,
                       sensitivity = cm[["byClass"]][["Sensitivity"]],
                       specificity = cm[["byClass"]][["Specificity"]])
      
      data$ActualClass <- ifelse(data$ActualClass == type2, 0, 1)
      
      roc <- roc(data$ActualClass, data[[type2]])
      specificity <- roc[["specificities"]]
      sensitivity <- roc[["sensitivities"]]
      sensitivity <- 1 - sensitivity
      
      roc <- as.data.frame(cbind(sensitivity, specificity))
      colnames(roc) <- c("sensitivity", "specificity")
      roc$Metric <- analysis
      
      auc <- auc(data$ActualClass, data[[type2]])
      auc <- format(signif(auc, digits = 3), nsmall = 3)
      auc <- data.frame(Metric = analysis, auc = auc)
      
      data_roc <- rbind(data_roc, roc)
      data_auc <- rbind(data_auc, auc)
      data_cm <- rbind(data_cm, cm)
    }
    
    # Function to get the appropriate labels for each unique metric
    get_labels <- function(unique_metrics) {
      label_mapping <- list(
        "DELFI_ratios" = "Fragment Ratio",
        "End_motif" = "End Motif",
        "Nucleosome_Peak" = "Nucleosome Peak",
        "Methylation" = "Methylation",
        "Combined_features_PCA" = "Combined All Features PCs >5%",
        "PCA_DELFI_ratios" = "PCA Fragment Ratio",
        "PCA_End_motif" = "PCA End Motif",
        "PCA_Insert_Size" = "PCA Insert Size",
        "PCA_Methylation" = "PCA Methylation",
        "PCA_Nucleosome_Peak" = "PCA Nucleosome Peak",
        "Combined_endmotif_methylation" = "End motif + methylation",
        "Combined_motif_methylation_PCs_1pct" = "End Motif + Methylation PCs >1%",
        "Combined_motif_methylation_ratios_PCs_1pct" = "End Motif + Methylation + Ratios PCs >1%"
      )
      
      sapply(unique_metrics, function(x) label_mapping[[x]])
    }
    
    unique_metrics <- unique(data_roc$Metric)
    
    data_roc$Metric <- factor(data_roc$Metric, levels = unique_metrics, labels = get_labels(unique_metrics))
    data_auc$Metric <- factor(data_auc$Metric, levels = unique_metrics, labels = get_labels(unique_metrics))
    data_cm$Metric <- factor(data_cm$Metric, levels = unique_metrics, labels = get_labels(unique_metrics))
    
    create_and_save_plots(data_roc, data_auc, data_cm, ifelse(filter_type == "PCA", "PCA", "all_features"))
  }
}



  ## Now get AUC data
  # Initialize an empty dataframe to store the combined AUC values
  all_data_auc <- data.frame()
  
  for (i in 1:nrow(unique_comparisons_df)) {
    
    # Set variables from the dataframe
    type1 <- unique_comparisons_df$type1[i]
    type2 <- unique_comparisons_df$type2[i]
    
    # Create a regex pattern to match type1 and type2 in either order
    pattern_to_search <- paste0("(", type1, "_vs_", type2, "|", type2, "_vs_", type1, ")\\.rds")
    
    # List files that match the pattern
    filenames_short <- list.files(path, pattern = pattern_to_search, full.names = FALSE)
    filenames <- list.files(path, pattern = pattern_to_search, full.names = TRUE)
    
    # Extract the analysis from the dataframe
    matching_rows <- classification_df_filtered$file %in% filenames_short
    analyses <- unique(classification_df_filtered$Analysis[matching_rows])
    
    data_roc <- data.frame()
    data_auc <- data.frame()
    data_cm <- data.frame()
    
    for (j in c(1:length(filenames))) {
      
      ### Set variables
      file <- filenames[[j]]
      analysis <- analyses[[j]]
      
      ### Read in file
      data <- readRDS(file)
      
      ### Unlist files
      data <- unlist(data, recursive = FALSE)
      data <- bind_rows(data)
      
      ### Make confusion matrix
      data$ActualClass <- factor(data$ActualClass, levels = c(type1, type2))
      data$PredictedClass <- factor(data$PredictedClass, levels = c(type1, type2))
      cm <- confusionMatrix(data$PredictedClass, data$ActualClass)
      cm <- data.frame(Metric = analysis,
                       sensitivity = cm[["byClass"]][["Sensitivity"]],
                       specificity = cm[["byClass"]][["Specificity"]])
      
      ### Format table
      data$ActualClass <- ifelse(data$ActualClass == type2, 0, 1)
      
      ### Calculate auc and roc values
      roc <- roc(data$ActualClass, data[[type2]])
      specificity <- roc[["specificities"]]
      sensitivity <- roc[["sensitivities"]]
      sensitivity <- 1 - sensitivity
      
      roc <- as.data.frame(cbind(sensitivity, specificity))
      colnames(roc) <- c("sensitivity", "specificity")
      roc$Metric <- analysis
      
      auc <- auc(data$ActualClass, data[[type2]])
      auc <- format(signif(auc, digits = 3), nsmall = 3)
      auc <- data.frame(Metric = analysis, auc = auc)
      
      ### Append to dataframes
      data_roc <- rbind(data_roc, roc)
      data_auc <- rbind(data_auc, auc)
      data_cm <- rbind(data_cm, cm)
      
      auc$Type1 <- type1
      auc$Type2 <- type2
      
      # Append to the all_data_auc dataframe
      all_data_auc <- rbind(all_data_auc, auc)
    }
  }
  
  ## Now make a heatmap based on AUC data
  ## For triangle format 
  # First, let's create a list of matrices, one for each Metric
  auc_matrices <- all_data_auc %>%
    split(.$Metric) %>%
    lapply(function(df) {
      # Convert AUC to numeric if it's not already
      df$auc <- as.numeric(as.character(df$auc))
      
      # Spread the dataframe to a wide format
      spread_df <- spread(df, key = Type2, value = auc)
      rownames(spread_df) <- spread_df$Type1
      
      # We only keep the upper triangle, so we set the lower triangle and diagonal to NA
      mat <- as.matrix(spread_df[,-c(1,2)])  # Assuming first two columns are Metric and Type1
      mat[lower.tri(mat, diag = TRUE)] <- NA
      mat
    })
  
  # Now let's plot the heatmaps without the diagonal and lower part
  library(ComplexHeatmap)
  library(circlize)
  
  ## Updated plots
  # Define a custom color scale
  auc_colors <- colorRamp2(c(0.5, 0.75, 1), c("#d0e1f9", "#74a9cf", "#0570b0"))
  
  
  ## If want it in square format
  # First, let's create a list of matrices, one for each Metric
  auc_matrices <- all_data_auc %>%
    split(.$Metric) %>%
    lapply(function(df) {
      # Convert AUC to numeric if it's not already
      df$auc <- as.numeric(as.character(df$auc))
      
      # Spread the dataframe to a wide format
      spread(df, key = Type2, value = auc)
    })
  
  # Now, let's remove the Metric column as it's not needed for the matrix
  auc_matrices <- lapply(auc_matrices, function(df) {
    rownames(df) <- df$Type1
    df <- as.matrix(df[,-c(1,2)])  # Assuming first two columns are Metric and Type1
    df
  })
  
  
  ## Creating the heatmaps - updated Feb 2024 - not looking as nice as below - use below
  for(metric in names(auc_matrices)) {
    heatmap_matrix <- auc_matrices[[metric]]
    
    # If "normal" is a row, make it the first row
    if("normal" %in% rownames(heatmap_matrix)) {
      heatmap_matrix <- heatmap_matrix[c("normal", setdiff(rownames(heatmap_matrix), "normal")), ]
    }
    
    # Define the file name for each plot
    file_name <- paste0(metric, "_AUC_heatmap_square.png") # Change extension to .png for PNG format
    
    # Start PNG device
    png(file.path(path, file_name), width = 10, height = 8, units = 'in', res = 300)
    
    # Create the heatmap with the defined color scale
    Heatmap(heatmap_matrix, 
            name = "AUC", 
            col = auc_colors, 
            cluster_rows = FALSE, 
            cluster_columns = FALSE, 
            show_row_names = TRUE, 
            show_column_names = TRUE,
            column_title = metric,
            row_title = "Cancer type",
            na_col = "white",
            cell_fun = function(j, i, x, y, width, height, fill) {
              if(!is.na(heatmap_matrix[i, j])) {
                grid.text(sprintf("%.3f", heatmap_matrix[i, j]), x, y, gp = gpar(fontsize = 10))
              }
            })
    
    # Close the PNG device
    dev.off()
  }
  
  
  # Creating the heatmaps - original - works better
  pdf("Heatmaps_per_Metric May 2024, updated colors.pdf") # Start the PDF device to save all plots to a single file
  for(metric in names(auc_matrices)) {
    # Create a heatmap for each metric
    heatmap_matrix <- auc_matrices[[metric]]
    
    # Replacing NA values with 0 for better visualization
    #  heatmap_matrix[is.na(heatmap_matrix)] <- 0 
    
    # Create the heatmap
    ht <- Heatmap(heatmap_matrix, 
                  name = "AUC", 
                  col = auc_colors, #added
                  cluster_rows = FALSE, 
                  cluster_columns = FALSE, 
                  show_row_names = TRUE, 
                  show_column_names = TRUE,
                  column_title = metric, 
                  row_title = "Cancer type",
                  cell_fun = function(j, i, x, y, width, height, fill) {
                    if(!is.na(heatmap_matrix[i, j])) {
                      grid.text(sprintf("%.3f", heatmap_matrix[i, j]), x, y, gp = gpar(fontsize = 10))
                    }
                  })
    
    # Draw the heatmap
    print(ht)
  }
  dev.off() # Close the PDF device
  
  
  
  
  
  
  
### Replot figure 4B
  # List all the .txt files in the directory
  path <- "Final Data May 2024/Machine_learning_outputs/Cancer_vs_normal/"

  file_list <- list.files(path, pattern = "*.txt", full.names = TRUE)
  
  # Function to read and clean each file
  read_and_clean <- function(file) {
    # Read the file
    data <- read.table(file, header = TRUE)
    
    # Add the filename as a new column
    data$filename <- basename(file)
    
    # Clean the filename to extract meaningful information
    data$filename <- str_replace_all(data$filename, "_results_healthy_vs_cancer.txt", "")
    data$filename <- str_replace_all(data$filename, "CN_classifier_", "")
    
    return(data)
  }
  
  # Import all files and combine into a single dataframe
  combined_data <- bind_rows(lapply(file_list, read_and_clean))
  
  # Filter rows where the filename contains "PC" since that is what interested in
  combined_data <- combined_data %>% filter(str_detect(filename, "PC"))
  
  # Function to get the appropriate labels for each unique metric
  get_labels <- function(unique_metrics) {
    label_mapping <- list(
      "DELFI_ratios" = "Fragment Ratio",
      "End_motif" = "End Motif",
      "Nucleosome_Peak" = "Nucleosome Peak",
      "Methylation" = "Methylation",
      "Combined_features_PCA" = "Combined All Features PCs >5%",
      "PCA_DELFI_ratios" = "PCA Fragment Ratio",
      "PCA_End_motif" = "PCA End Motif",
      "PCA_Insert_Size" = "PCA Insert Size",
      "PCA_Methylation" = "PCA Methylation",
      "PCA_Nucleosome_Peak" = "PCA Nucleosome Peak",
      "Combined_endmotif_methylation" = "End motif + methylation",
      "Combined_motif_methylation_PCs_1pct" = "End Motif + Methylation PCs >1%",
      "Combined_motif_methylation_ratios_PCs_1pct" = "End Motif + Methylation + Ratios PCs >1%"
    )
    
    sapply(unique_metrics, function(x) label_mapping[[x]])
  }
  
  # Apply the get_labels function to the filename column
  combined_data$technology <- get_labels(combined_data$filename)
  
  ## Make factor so can use with ggplot
  combined_data$technology <- as.character(combined_data$technology)
  combined_data$technology <- factor(combined_data$technology)
  
  # Define your color palette
  my_color_palette <- c(
    "Fragment Ratio" = "#1f77b4",
    "End Motif" = "#ff7f0e",
    "Nucleosome Peak" = "#2ca02c",
    "Methylation" = "#d62728",
    "Combined All Features PCs >5%" = "#9467bd",
    "PCA Fragment Ratio" = "#17becf",
    "PCA End Motif" = "#bcbd22",
    "PCA Insert Size" = "#e377c2",
    "PCA Methylation" = "#7f7f7f",
    "PCA Nucleosome Peak" = "#8c564b",
    "End Motif + Methylation PCs >1%" = "#8B0000",  # Dark Red
    "End Motif + Methylation + Ratios PCs >1%" = "#32CD32"  # Lime Green
  )
  
  # Plot the data
  ggplot(combined_data, aes(x = kappa, y = reorder(test, kappa), color = technology)) +
    geom_point() +
    geom_errorbarh(aes(xmin = kappa - error, xmax = kappa + error), height = 0.2) +
    scale_color_manual(values = my_color_palette) +
    theme_classic() +
    labs(title = "Classifier Performance",
         x = "Kappa",
         y = "Algorithm",
         color = "Technology") +
    theme(legend.position = "bottom", legend.text = element_text(size = 6))
  
  # Save the plot
  ggsave("classifier_performance_plot.pdf", width = 8, height = 6)
  
  
  
  
  
  
  
  
  ### Testing 
  ## Run on PCAs seperately
  for (i in 1:nrow(unique_comparisons_df)) {
    
    # Set variables from the dataframe
    type1 <- unique_comparisons_df$type1[i]
    type2 <- unique_comparisons_df$type2[i]
    
    # Create a regex pattern to match type1 and type2 in either order
    pattern_to_search <- paste0("(", type1, "_vs_", type2, "|", type2, "_vs_", type1, ")\\.rds")
    
    # List files that match the pattern
    filenames_short <- list.files(path, pattern = pattern_to_search, full.names = FALSE)
    filenames <- list.files(path, pattern = pattern_to_search, full.names = TRUE)
    
    # Function to create and save plots
    create_and_save_plots <- function(data_roc, data_auc, data_cm, suffix) {
      # Count the number of rows in data_auc
      n_rows <- nrow(data_auc)
      
      # Create a sequence for the y aesthetic
      y_values <- seq(0, 0.3, length.out = n_rows)
      
      # Add the y_values to data_auc
      data_auc$y_values <- y_values
      
      # Define colors 
      my_color_palette <- c(
        "Fragment Ratio" = "#1f77b4",
        "End Motif" = "#ff7f0e",
        "Nucleosome Peak" = "#2ca02c",
        "Methylation" = "#d62728",
        "Combined Features PCA" = "#9467bd",
        "PCA Fragment Ratio" = "#17becf",
        "PCA End Motif" = "#bcbd22",
        "PCA Insert Size" = "#e377c2",
        "PCA Methylation" = "#7f7f7f",
        "PCA Nucleosome Peak" = "#8c564b",
        "End motif + methylation" = "#8B0000",  # Dark Red
        "End Motif + Methylation PCs >1%" = "#1E90FF",  # Dodger Blue
        "Combined Motif + Methylation All PCs" = "#32CD32",  # Lime Green
        "Combined Motif + Methylation + Ratios PCs >1%" = "#FFD700"  # Gold
      )
      
      AUC_plot <- ggplot(data_roc) +
        geom_line(aes(sensitivity, specificity, group = Metric, color = Metric)) +
        geom_abline(intercept = 0, linetype = "dashed", alpha = 0.5) +
        geom_text(data = data_auc, aes(x = 0.7, y = seq(0, 0.34, length.out = n_rows), color = Metric, label = paste0(Metric, " = ", auc)), size = 4) +
        scale_color_manual(values = my_color_palette) + 
        xlab("False Positive Rate") + 
        ylab("True Positive Rate") +
        ggtitle("ROC Curves") + 
        theme +
        theme(legend.position = "none")
      AUC_plot
      
      CM_plot <- ggplot(data_cm) +
        geom_point(aes(sensitivity, specificity, color = Metric), size = 3) +
        geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey") +
        geom_vline(xintercept = 0.5, linetype = "dashed", color = "grey") +
        scale_color_manual(values = my_color_palette) + 
        xlab("Sensitivity") + 
        ylab("Specificity") +
        labs(color = "") +
        ggtitle("Performance") + 
        theme +
        theme(legend.position = c(0.5, 0.21)) +
        scale_y_continuous(limits = c(0,1)) +
        scale_x_continuous(limits = c(0,1)) +
        guides(color = guide_legend(ncol = 2))
      CM_plot
      
      fig <- ggarrange(AUC_plot, CM_plot, align = "h")
      annotate_figure(fig, top = text_grob(paste0(type1, " vs ", type2), face = "bold", size = 14))
      ggsave(file.path(path, paste0("classifier_performance_", type1, "_vs_", type2, "_", suffix, "combined updated.pdf")), width = 9, height = 4.5)
    }
    
    for (filter_type in c("all", "PCA")) {
      if (filter_type == "PCA") {
        filtered_classification_df <- classification_df %>% filter(str_detect(Analysis, "PC"))
      } else {
        filtered_classification_df <- classification_df
      }
      
      # Extract the analysis and filenames from the filtered dataframe
      filtered_filenames_short <- filtered_classification_df$file
      filtered_analyses <- filtered_classification_df$Analysis
      
      data_roc <- data.frame()
      data_auc <- data.frame()
      data_cm <- data.frame()
      
      for (j in seq_along(filenames)) {
        file <- filenames[[j]]
        filename_short <- filenames_short[[j]]
        
        if (!(filename_short %in% filtered_filenames_short)) next
        
        analysis <- filtered_analyses[filtered_filenames_short == filename_short]
        
        data <- readRDS(file)
        data <- unlist(data, recursive = FALSE)
        data <- bind_rows(data)
        
        data$ActualClass <- factor(data$ActualClass, levels = c(type1, type2))
        data$PredictedClass <- factor(data$PredictedClass, levels = c(type1, type2))
        cm <- confusionMatrix(data$PredictedClass, data$ActualClass)
        cm <- data.frame(Metric = analysis,
                         sensitivity = cm[["byClass"]][["Sensitivity"]],
                         specificity = cm[["byClass"]][["Specificity"]])
        
        data$ActualClass <- ifelse(data$ActualClass == type2, 0, 1)
        
        roc <- roc(data$ActualClass, data[[type2]])
        specificity <- roc[["specificities"]]
        sensitivity <- roc[["sensitivities"]]
        sensitivity <- 1 - sensitivity
        
        roc <- as.data.frame(cbind(sensitivity, specificity))
        colnames(roc) <- c("sensitivity", "specificity")
        roc$Metric <- analysis
        
        auc <- auc(data$ActualClass, data[[type2]])
        auc <- format(signif(auc, digits = 3), nsmall = 3)
        auc <- data.frame(Metric = analysis, auc = auc)
        
        data_roc <- rbind(data_roc, roc)
        data_auc <- rbind(data_auc, auc)
        data_cm <- rbind(data_cm, cm)
      }
      
      # Function to get the appropriate labels for each unique metric
      get_labels <- function(unique_metrics) {
        label_mapping <- list(
          "DELFI_ratios" = "Fragment Ratio",
          "End_motif" = "End Motif",
          "Nucleosome_Peak" = "Nucleosome Peak",
          "Methylation" = "Methylation",
          "Combined_features_PCA" = "Combined Features PCA",
          "PCA_DELFI_ratios" = "PCA Fragment Ratio",
          "PCA_End_motif" = "PCA End Motif",
          "PCA_Insert_Size" = "PCA Insert Size",
          "PCA_Methylation" = "PCA Methylation",
          "PCA_Nucleosome_Peak" = "PCA Nucleosome Peak",
          "Combined_endmotif_methylation" = "End motif + methylation",
          "Combined_motif_methylation_PCs_1pct" = "Combined Motif + Methylation PCs >1%",
          "Combined_motif_methylation_PCs_all" = "Combined Motif + Methylation All PCs",
          "Combined_motif_methylation_ratios_PCs_1pct" = "Combined Motif + Methylation + Ratios PCs >1%"
        )
        
        sapply(unique_metrics, function(x) label_mapping[[x]])
      }
      
      unique_metrics <- unique(data_roc$Metric)
      
      data_roc$Metric <- factor(data_roc$Metric, levels = unique_metrics, labels = get_labels(unique_metrics))
      data_auc$Metric <- factor(data_auc$Metric, levels = unique_metrics, labels = get_labels(unique_metrics))
      data_cm$Metric <- factor(data_cm$Metric, levels = unique_metrics, labels = get_labels(unique_metrics))
      
      create_and_save_plots(data_roc, data_auc, data_cm, ifelse(filter_type == "PCA", "PCA", "all_features"))
    }
  }
  